import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";

const navLinks = [
  { name: "Register", href: "/register" },
  { name: "Login", herf: "/login" },
  { name: "Forgot Password", href: "/forgot-password" },
];

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

        <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "1 rem",
          }}
        >
          <p>Footer </p>
        </footer>
      </body>
    </html>
  );
}
