import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ErrorWrapper } from "./error-wrapper";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Ravi's next js temp",
    template: "%s | ravikumar",
    absolute: "",
  },
  description: "Generated by create next app",
};

export default function MarketingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header
          style={{
            backgroundColor: "lightblue",
            padding: "1rem",
          }}
        >
          <h1>Header</h1>
        </header>
        <ErrorWrapper>{children}</ErrorWrapper>

        <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "1 rem",
          }}
        >
          <p>Footer </p>
        </footer>
      </body>
    </html>
  );
}
